Parameters:
  ImageId:
    Type: String
  InstanceTypeParameter:
    Type: String
  
Resources:
  MyFirstS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "rt-b4-demo-2"
      WebsiteConfiguration:
        IndexDocument: index.html      
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceTypeParameter
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 20

Outputs: 
  InstanceId:
    Value: !Ref MyEC2Instance
  PrivateIp:
    Value: !GetAtt MyEC2Instance.PrivateIp
  S3StaticWebsiteEndpoint:
    Value: !GetAtt MyFirstS3Bucket.WebsiteURL 
